name: Data64
version: ${project.version}
description: ${project.description}
author: tbm00
main: dev.tbm00.spigot.data64.Data64
api-version: 1.17
depend: [DisplayShops, GriefDefender, Essentials, PlayerWarps]
commands:
  dataadmin:
    description: Main command for Data64
permissions:
  data64.cmd:
    description: Ability to use the /dataadmin command
    default: op