name: Reset64
version: ${project.version}
description: ${project.description}
author: tbm00
main: dev.tbm00.spigot.reset64.Reset64
api-version: 1.17
depend: []
commands:
  reset:
    description: Main command for Reset64
permissions:
  reset64.cmd.base:
    description: Ability to use the /reset base-command
    default: op
  reset64.cmd.sub:
    description: Ability to use the /reset sub-command
    default: op