name: Reset64
version: ${project.version}
description: ${project.description}
author: tbm00
main: dev.tbm00.spigot.reset64.Reset64
api-version: 1.17
depend: [DisplayShops]
commands:
  reset:
    description: Main command for Reset64
permissions:
  reset64.cmd:
    description: Ability to use the /reset command
    default: op